"""
SupplyGuard Data Repository Service
Unified data access layer providing real-time queries, analytical aggregations,
ML risk scoring cache, alert triage, and corrective action workflows.
"""

import os
import json
import uuid
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional

import pandas as pd
import numpy as np

from backend.core.security import get_password_hash
from risk_engine.features import RiskFeatureExtractor
from risk_engine.model import ExplainableSupplierRiskModel, ExplainableStockoutRiskModel
from risk_engine.explainer import RiskNarrativeExplainer


class SupplyGuardRepository:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(SupplyGuardRepository, cls).__new__(cls)
            cls._instance.initialized = False
        return cls._instance

    def __init__(self):
        if self.initialized:
            return
        self.data_dir = os.getenv("DATA_DIR", "data")
        self._load_datasets()
        self._init_models_and_scores()
        self._init_operational_state()
        self.initialized = True

    def _load_datasets(self):
        # Load CSV data generated by data_generator
        self.suppliers_df = pd.read_csv(os.path.join(self.data_dir, "suppliers.csv"))
        self.materials_df = pd.read_csv(os.path.join(self.data_dir, "materials.csv"))
        self.pos_df = pd.read_csv(os.path.join(self.data_dir, "purchase_orders.csv"))
        self.po_lines_df = pd.read_csv(os.path.join(self.data_dir, "purchase_order_lines.csv"))
        self.receipts_df = pd.read_csv(os.path.join(self.data_dir, "goods_receipts.csv"))
        self.inspections_df = pd.read_csv(os.path.join(self.data_dir, "quality_inspections.csv"))
        self.movements_df = pd.read_csv(os.path.join(self.data_dir, "inventory_movements.csv"))
        self.work_orders_df = pd.read_csv(os.path.join(self.data_dir, "production_schedules.csv"))
        self.bom_df = pd.read_csv(os.path.join(self.data_dir, "bom_allocations.csv"))

    def _init_models_and_scores(self):
        # 1. Train and Score Supplier Risk Model
        self.sup_features_df = RiskFeatureExtractor.extract_supplier_features(
            self.suppliers_df, self.receipts_df, self.inspections_df, self.pos_df, self.materials_df
        )
        self.sup_model = ExplainableSupplierRiskModel()
        self.supplier_predictions = self.sup_model.predict_and_explain(self.sup_features_df)
        self.supplier_score_lookup = {p["supplier_id"]: p for p in self.supplier_predictions}

        # 2. Train and Score Material Stockout Risk Model
        self.mat_features_df = RiskFeatureExtractor.extract_material_features(
            self.materials_df, self.movements_df, self.pos_df, self.bom_df
        )
        self.stockout_model = ExplainableStockoutRiskModel()
        self.material_predictions = self.stockout_model.predict_and_explain(self.mat_features_df)
        self.material_score_lookup = {p["material_id"]: p for p in self.material_predictions}

    def _init_operational_state(self):
        # Users seed
        self.users = {
            "admin": {
                "user_id": "USR-001",
                "username": "admin",
                "email": "admin@supplyguard.internal",
                "full_name": "Chief Supply Chain Officer",
                "role": "ADMIN",
                "hashed_password": get_password_hash("admin123")
            },
            "analyst": {
                "user_id": "USR-002",
                "username": "analyst",
                "email": "analyst@supplyguard.internal",
                "full_name": "Senior DI Engineer",
                "role": "ANALYST",
                "hashed_password": get_password_hash("analyst123")
            },
            "procurement": {
                "user_id": "USR-003",
                "username": "procurement",
                "email": "procurement@supplyguard.internal",
                "full_name": "Lead Strategic Procurement Manager",
                "role": "PROCUREMENT_LEAD",
                "hashed_password": get_password_hash("procurement123")
            }
        }

        # Seed initial operational Alerts from High/Critical risks
        self.alerts: Dict[str, Dict[str, Any]] = {}
        alert_counter = 1
        now = datetime.utcnow()

        # Seed Critical Stockout Alerts
        for p in self.material_predictions:
            if p["risk_tier"] == "CRITICAL" and alert_counter <= 15:
                aid = f"ALT-STK-{alert_counter:04d}"
                expl = RiskNarrativeExplainer.generate_stockout_explanation(p)
                self.alerts[aid] = {
                    "alert_id": aid,
                    "alert_type": "STOCKOUT",
                    "severity": "CRITICAL",
                    "title": f"Critical Stockout Breach: SKU {p.get('sku', p['material_id'])}",
                    "message": expl,
                    "entity_type": "MATERIAL",
                    "entity_id": p["material_id"],
                    "impact_valuation": round(float(p["days_of_inventory"] * 450.0), 2),
                    "status": "ACTIVE",
                    "created_at": now - timedelta(hours=alert_counter * 3),
                    "resolved_at": None
                }
                alert_counter += 1

        # Seed High/Critical Supplier Risk Alerts
        for p in self.supplier_predictions:
            if p["risk_tier"] in ("CRITICAL", "HIGH") and alert_counter <= 30:
                aid = f"ALT-SUP-{alert_counter:04d}"
                expl = RiskNarrativeExplainer.generate_supplier_explanation(p)
                self.alerts[aid] = {
                    "alert_id": aid,
                    "alert_type": "HIGH_RISK_SUPPLIER",
                    "severity": p["risk_tier"],
                    "title": f"Vendor Performance Deterioration: {p.get('supplier_name', p['supplier_id'])}",
                    "message": expl,
                    "entity_type": "SUPPLIER",
                    "entity_id": p["supplier_id"],
                    "impact_valuation": round(float(p["financial_risk_score"] * 320.0), 2),
                    "status": "ACTIVE",
                    "created_at": now - timedelta(hours=alert_counter * 2),
                    "resolved_at": None
                }
                alert_counter += 1

        # Seed Corrective Actions
        self.corrective_actions: Dict[str, Dict[str, Any]] = {}
        sample_alerts = list(self.alerts.values())[:6]
        for idx, alt in enumerate(sample_alerts, 1):
            act_id = f"CA-2026-{idx:04d}"
            status = "IN_PROGRESS" if idx % 2 == 0 else "OPEN"
            self.corrective_actions[act_id] = {
                "action_id": act_id,
                "alert_id": alt["alert_id"],
                "title": f"Mitigation Protocol: {alt['title']}",
                "description": f"Expedite root-cause analysis and execute alternate supply routing. Alert: {alt['message']}",
                "assigned_to": "Lead Strategic Procurement Manager" if idx % 2 == 0 else "Senior DI Engineer",
                "priority": alt["severity"],
                "status": status,
                "root_cause": "Tier-2 raw material supply bottleneck at regional port facility." if status == "IN_PROGRESS" else None,
                "mitigation_plan": "Initiate air freight spot order for 500 units; dual-source qualification pending engineering review." if status == "IN_PROGRESS" else None,
                "resolution_notes": None,
                "target_completion_date": (now + timedelta(days=7)).date(),
                "created_at": alt["created_at"],
                "updated_at": now - timedelta(hours=idx * 2),
                "resolved_at": None
            }

        # Seed ETL Audit Logs
        self.etl_audit_logs = [
            {
                "run_id": str(uuid.uuid4()),
                "pipeline_name": "AIRFLOW_INGESTION_PIPELINE",
                "batch_id": "BATCH-2026-04-15-01",
                "start_time": now - timedelta(hours=4),
                "end_time": now - timedelta(hours=3, minutes=56),
                "duration_seconds": 240.5,
                "rows_extracted": 128450,
                "rows_loaded": 128385,
                "rows_rejected": 65,
                "status": "SUCCESS",
                "error_message": None
            },
            {
                "run_id": str(uuid.uuid4()),
                "pipeline_name": "AIRFLOW_WAREHOUSE_TRANSFORM",
                "batch_id": "BATCH-2026-04-15-02",
                "start_time": now - timedelta(hours=3, minutes=50),
                "end_time": now - timedelta(hours=3, minutes=45),
                "duration_seconds": 312.0,
                "rows_extracted": 110000,
                "rows_loaded": 110000,
                "rows_rejected": 0,
                "status": "SUCCESS",
                "error_message": None
            },
            {
                "run_id": str(uuid.uuid4()),
                "pipeline_name": "AIRFLOW_DATA_QUALITY_SUITE",
                "batch_id": "BATCH-2026-04-15-03",
                "start_time": now - timedelta(hours=3, minutes=40),
                "end_time": now - timedelta(hours=3, minutes=38),
                "duration_seconds": 125.0,
                "rows_extracted": 7,
                "rows_loaded": 7,
                "rows_rejected": 0,
                "status": "SUCCESS",
                "error_message": None
            },
            {
                "run_id": str(uuid.uuid4()),
                "pipeline_name": "AIRFLOW_ML_RISK_SCORING",
                "batch_id": "BATCH-2026-04-15-04",
                "start_time": now - timedelta(hours=3, minutes=30),
                "end_time": now - timedelta(hours=3, minutes=27),
                "duration_seconds": 180.2,
                "rows_extracted": 1320,
                "rows_loaded": 1320,
                "rows_rejected": 0,
                "status": "SUCCESS",
                "error_message": None
            }
        ]

        # Seed ETL Dead-Letter Rejected Records
        self.etl_rejected_records = [
            {
                "rejection_id": 1,
                "pipeline_name": "AIRFLOW_INGESTION_PIPELINE",
                "source_table": "raw_materials",
                "payload": json.dumps({"material_id": "MAT-00999", "sku": "SKU-DUP-01", "reorder_point": 10, "safety_stock_level": 50}),
                "error_code": "ERR_SCHEMA_VALIDATION",
                "error_reason": "Reorder point (10) must be greater than or equal to safety stock (50)",
                "rejected_at": now - timedelta(hours=4)
            },
            {
                "rejection_id": 2,
                "pipeline_name": "AIRFLOW_INGESTION_PIPELINE",
                "source_table": "raw_purchase_orders",
                "payload": json.dumps({"po_id": "PO-2025-9999", "order_date": "2025-05-10", "promised_delivery_date": "2025-05-01"}),
                "error_code": "ERR_SCHEMA_VALIDATION",
                "error_reason": "Promised delivery date (2025-05-01) cannot be before order date (2025-05-10)",
                "rejected_at": now - timedelta(hours=4)
            },
            {
                "rejection_id": 3,
                "pipeline_name": "AIRFLOW_INGESTION_PIPELINE",
                "source_table": "raw_suppliers",
                "payload": json.dumps({"supplier_id": "SUP-0012", "code": "VND-DUP", "tier": "TIER_99"}),
                "error_code": "ERR_SCHEMA_VALIDATION",
                "error_reason": "Invalid supplier tier: TIER_99. Expected one of {'TIER_1', 'TIER_2', 'TIER_3'}",
                "rejected_at": now - timedelta(hours=4)
            }
        ]

        # Seed Data Quality Assertions
        self.data_quality_results = [
            {
                "test_id": 1,
                "test_name": "assert_non_negative_inventory_balance",
                "target_table": "fact_inventory_movements",
                "assertion_type": "RANGE",
                "metric_value": 0.0,
                "threshold": 0.0,
                "status": "PASS",
                "severity": "CRITICAL",
                "details": "All warehouse cumulative balances are non-negative.",
                "executed_at": now - timedelta(hours=3, minutes=38)
            },
            {
                "test_id": 2,
                "test_name": "assert_no_orphaned_goods_receipts",
                "target_table": "fact_goods_receipts",
                "assertion_type": "REFERENTIAL",
                "metric_value": 0.0,
                "threshold": 0.0,
                "status": "PASS",
                "severity": "CRITICAL",
                "details": "100% referential integrity verified between goods receipts and purchase orders.",
                "executed_at": now - timedelta(hours=3, minutes=38)
            },
            {
                "test_id": 3,
                "test_name": "assert_delivery_date_chronology",
                "target_table": "fact_goods_receipts",
                "assertion_type": "POSITIVE_VALUE",
                "metric_value": 0.0,
                "threshold": 0.0,
                "status": "PASS",
                "severity": "HIGH",
                "details": "All delivery receipts satisfy actual_receipt_date >= order_date.",
                "executed_at": now - timedelta(hours=3, minutes=38)
            },
            {
                "test_id": 4,
                "test_name": "assert_quality_ppm_within_physical_bounds",
                "target_table": "fact_quality_inspections",
                "assertion_type": "RANGE",
                "metric_value": 0.0,
                "threshold": 0.0,
                "status": "PASS",
                "severity": "MEDIUM",
                "details": "Defect PPM metrics within valid range [0, 1,000,000].",
                "executed_at": now - timedelta(hours=3, minutes=38)
            },
            {
                "test_id": 5,
                "test_name": "monitor_work_order_shortage_rate",
                "target_table": "fact_bom_allocations",
                "assertion_type": "RANGE",
                "metric_value": 9.8,
                "threshold": 25.0,
                "status": "PASS",
                "severity": "MEDIUM",
                "details": "Active work order shortage rate is 9.8%, within permissible 25% threshold.",
                "executed_at": now - timedelta(hours=3, minutes=38)
            }
        ]

    # Query APIs
    def get_kpis(self) -> Dict[str, Any]:
        total_pos = len(self.pos_df)
        delivered_pos = len(self.receipts_df)
        otd_rate = round(float((self.receipts_df["delivery_variance_days"] <= 0).mean() * 100.0), 1)

        overdue_df = self.pos_df[self.pos_df["status"] == "OVERDUE"]
        spend_at_risk = round(float(overdue_df["total_amount"].sum()), 2)

        stockouts = sum(1 for p in self.material_predictions if p["days_of_inventory"] <= 0 or p["risk_tier"] == "CRITICAL")
        
        # Total inventory valuation
        inv_val = round(float((self.mat_features_df["current_stock"] * self.mat_features_df["standard_cost"]).sum()), 2)
        avg_doi = round(float(self.mat_features_df["days_of_inventory"].median()), 1)

        high_risk_sups = sum(1 for p in self.supplier_predictions if p["risk_tier"] in ("CRITICAL", "HIGH"))
        active_alerts = sum(1 for a in self.alerts.values() if a["status"] == "ACTIVE")
        open_actions = sum(1 for c in self.corrective_actions.values() if c["status"] in ("OPEN", "IN_PROGRESS"))

        return {
            "on_time_delivery_rate": otd_rate,
            "total_spend_at_risk_usd": spend_at_risk,
            "active_stockouts_count": stockouts,
            "total_inventory_valuation_usd": inv_val,
            "average_days_of_inventory": avg_doi,
            "high_risk_suppliers_count": high_risk_sups,
            "active_alerts_count": active_alerts,
            "open_corrective_actions_count": open_actions
        }

    def get_suppliers(
        self, 
        tier: Optional[str] = None, 
        category: Optional[str] = None, 
        risk_tier: Optional[str] = None,
        search: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        results = []
        for p in self.supplier_predictions:
            s_info = self.suppliers_df[self.suppliers_df["supplier_id"] == p["supplier_id"]].iloc[0]
            if tier and s_info["tier"] != tier:
                continue
            if category and s_info["category"] != category:
                continue
            if risk_tier and p["risk_tier"] != risk_tier:
                continue
            if search:
                s_lower = search.lower()
                if s_lower not in s_info["name"].lower() and s_lower not in s_info["code"].lower() and s_lower not in s_info["supplier_id"].lower():
                    continue

            # Overdue spend
            sup_pos = self.pos_df[self.pos_df["supplier_id"] == p["supplier_id"]]
            overdue_spend = sup_pos[sup_pos["status"] == "OVERDUE"]["total_amount"].sum()
            total_spend = sup_pos["total_amount"].sum()

            results.append({
                "supplier_id": p["supplier_id"],
                "code": s_info["code"],
                "name": s_info["name"],
                "category": s_info["category"],
                "country": s_info["country"],
                "city": s_info["city"],
                "tier": s_info["tier"],
                "reliability_rating": s_info["reliability_rating"],
                "financial_health_score": s_info["financial_health_score"],
                "otd_percentage": p["otd_rate_90d"],
                "avg_lead_time_variance_days": p["lead_time_variance_avg"],
                "lead_time_variance_std": round(float(p.get("lead_time_variance_std", 2.1)), 1),
                "overall_defect_ppm": p["defect_ppm_90d"],
                "total_spend": round(float(total_spend), 2),
                "overdue_spend": round(float(overdue_spend), 2),
                "risk_score": p["risk_score"],
                "risk_tier": p["risk_tier"],
                "top_contributing_factors": p["top_contributing_factors"],
                "explanation_text": RiskNarrativeExplainer.generate_supplier_explanation(p)
            })

        results.sort(key=lambda x: x["risk_score"], reverse=True)
        return results

    def get_supplier_by_id(self, supplier_id: str) -> Optional[Dict[str, Any]]:
        sups = self.get_suppliers(search=supplier_id)
        for s in sups:
            if s["supplier_id"] == supplier_id:
                return s
        return None

    def get_materials(
        self,
        category: Optional[str] = None,
        risk_tier: Optional[str] = None,
        is_critical: Optional[bool] = None,
        search: Optional[str] = None,
        limit: int = 200
    ) -> List[Dict[str, Any]]:
        results = []
        for p in self.material_predictions:
            m_info = self.materials_df[self.materials_df["material_id"] == p["material_id"]].iloc[0]
            if category and m_info["category"] != category:
                continue
            if risk_tier and p["risk_tier"] != risk_tier:
                continue
            if is_critical is not None and m_info["is_critical"] != is_critical:
                continue
            if search:
                s_lower = search.lower()
                if s_lower not in m_info["name"].lower() and s_lower not in m_info["sku"].lower():
                    continue

            current_stock = p["current_stock"]
            safety = m_info["safety_stock_level"]
            reorder = m_info["reorder_point"]

            if current_stock <= 0:
                health = "STOCKOUT"
            elif current_stock < safety:
                health = "SAFETY_STOCK_BREACH"
            elif current_stock < reorder:
                health = "REORDER_TRIGGER"
            else:
                health = "HEALTHY"

            results.append({
                "material_id": p["material_id"],
                "sku": m_info["sku"],
                "name": m_info["name"],
                "category": m_info["category"],
                "unit_of_measure": m_info["unit_of_measure"],
                "standard_cost": m_info["standard_cost"],
                "safety_stock_level": safety,
                "reorder_point": reorder,
                "current_stock": current_stock,
                "days_of_inventory": p["days_of_inventory"],
                "stock_health_status": health,
                "is_critical": bool(m_info["is_critical"]),
                "stockout_risk_score": p["stockout_risk_score"],
                "risk_tier": p["risk_tier"],
                "explanation_text": RiskNarrativeExplainer.generate_stockout_explanation(p)
            })

        results.sort(key=lambda x: x["stockout_risk_score"], reverse=True)
        return results[:limit]

    def get_purchase_orders(
        self,
        status: Optional[str] = None,
        supplier_id: Optional[str] = None,
        search: Optional[str] = None,
        limit: int = 150
    ) -> List[Dict[str, Any]]:
        df = self.pos_df.copy()
        if status:
            df = df[df["status"] == status]
        if supplier_id:
            df = df[df["supplier_id"] == supplier_id]

        sup_map = self.suppliers_df.set_index("supplier_id")["name"].to_dict()
        results = []
        now = datetime(2026, 4, 15)

        for _, row in df.iterrows():
            if search:
                s_lower = search.lower()
                if s_lower not in row["po_number"].lower() and s_lower not in row["po_id"].lower():
                    continue

            p_date = datetime.strptime(row["promised_delivery_date"], "%Y-%m-%d")
            overdue_days = max(0, (now - p_date).days) if row["status"] == "OVERDUE" else 0

            results.append({
                "po_id": row["po_id"],
                "po_number": row["po_number"],
                "supplier_id": row["supplier_id"],
                "supplier_name": sup_map.get(row["supplier_id"], ""),
                "order_date": row["order_date"],
                "promised_delivery_date": row["promised_delivery_date"],
                "status": row["status"],
                "total_amount": float(row["total_amount"]),
                "currency": row.get("currency", "USD"),
                "days_overdue": overdue_days
            })

        results.sort(key=lambda x: (x["status"] == "OVERDUE", x["days_overdue"]), reverse=True)
        return results[:limit]

    def get_alerts(self, severity: Optional[str] = None, alert_type: Optional[str] = None) -> List[Dict[str, Any]]:
        items = list(self.alerts.values())
        if severity:
            items = [a for a in items if a["severity"] == severity]
        if alert_type:
            items = [a for a in items if a["alert_type"] == alert_type]
        items.sort(key=lambda x: x["created_at"], reverse=True)
        return items

    def update_alert_status(self, alert_id: str, status: str) -> Optional[Dict[str, Any]]:
        if alert_id in self.alerts:
            self.alerts[alert_id]["status"] = status
            if status == "RESOLVED":
                self.alerts[alert_id]["resolved_at"] = datetime.utcnow()
            return self.alerts[alert_id]
        return None

    def get_corrective_actions(self, status: Optional[str] = None) -> List[Dict[str, Any]]:
        items = list(self.corrective_actions.values())
        if status:
            items = [c for c in items if c["status"] == status]
        items.sort(key=lambda x: x["updated_at"], reverse=True)
        return items

    def create_corrective_action(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        action_id = f"CA-2026-{len(self.corrective_actions) + 1:04d}"
        now = datetime.utcnow()
        new_act = {
            "action_id": action_id,
            "alert_id": payload.get("alert_id"),
            "title": payload["title"],
            "description": payload["description"],
            "assigned_to": payload["assigned_to"],
            "priority": payload.get("priority", "HIGH"),
            "status": "OPEN",
            "root_cause": payload.get("root_cause"),
            "mitigation_plan": payload.get("mitigation_plan"),
            "resolution_notes": None,
            "target_completion_date": payload.get("target_completion_date"),
            "created_at": now,
            "updated_at": now,
            "resolved_at": None
        }
        self.corrective_actions[action_id] = new_act
        return new_act

    def update_corrective_action(self, action_id: str, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        if action_id not in self.corrective_actions:
            return None
        act = self.corrective_actions[action_id]
        for k, v in payload.items():
            if v is not None:
                act[k] = v
        act["updated_at"] = datetime.utcnow()
        if act.get("status") == "RESOLVED" and not act.get("resolved_at"):
            act["resolved_at"] = datetime.utcnow()
        return act

    def get_etl_audit_logs(self) -> List[Dict[str, Any]]:
        return sorted(self.etl_audit_logs, key=lambda x: x["start_time"], reverse=True)

    def get_etl_rejected_records(self) -> List[Dict[str, Any]]:
        return sorted(self.etl_rejected_records, key=lambda x: x["rejected_at"], reverse=True)

    def get_data_quality_results(self) -> List[Dict[str, Any]]:
        return sorted(self.data_quality_results, key=lambda x: x["executed_at"], reverse=True)
